{% set version = "1.5.2" %}
{% set name = "pylibmc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc54e28a9f1b5b2ec0c030da29c7ad8a15c2755bd98aaa4142eaf419d5fabb33

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libmemcached
    - python
  run:
    - libmemcached
    - python

test:
  source_files:
    - tests
  requires:
    - python
  imports:
    - _pylibmc
    - pylibmc

about:
  home: https://github.com/lericson/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Quick and small memcached client for Python

extra:
  recipe-maintainers:
    - bollwyvl
