{% set version = "1.6.2" %}
{% set name = "pylibmc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41ab49d39540767374891bef0beb5291ca97beb7048b7af77521064953c04dc0

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libmemcached
    - pip
    - python
  run:
    - libmemcached
    - python

test:
  imports:
    - _pylibmc
    - pylibmc

about:
  home: https://github.com/lericson/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Quick and small memcached client for Python

extra:
  recipe-maintainers:
    - bollwyvl
