{% set version = "1.6.0" %}
{% set name = "pylibmc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ef97be4ca5527d5b87dbe77cfdd94b427028caf4136feff7da23c40e1ded6d8

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libmemcached
    - pip
    - python
  run:
    - libmemcached
    - python

test:
  imports:
    - _pylibmc
    - pylibmc

about:
  home: https://github.com/lericson/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Quick and small memcached client for Python

extra:
  recipe-maintainers:
    - bollwyvl
