travis:
  secure:
    BINSTAR_TOKEN: vZJRd5wyjDRQ/r2CAQWbf6zzRldIL88BsTJllpFkpSlctY0/yp++U7us6etJRy3l271QcGpjGQWLzgvrAztp0SdpIhVHXTlkmnQ2Vd/tvVos0l/nzPkUJUO7nG5vr0nsli+PtLhdg++xRgczgF9cfc6vr3bdb03I0F9qQ5wUYwK6vckGYndq9hrCvdvxlFkHHkptf/UCBWyJO3rte89U0GT0vdszWQaFMjgl7f+Dpb1z+3PiZ1Wi/6HLdAl9/kFfOttxjXrNxPEa5hhjobx114Tv9IYH1fuW6WMcd3k4MTTRWZ9V8ci20C9aL2lbtpQd5lFYawjDGHitXf56Zblgu3Kfqt5oQnPBCVm87xlX3hkkdic7TpG0vwRRm0ldcW1++D1gnXWZ3D4EdWXXcU4EtAR9rJp8JorkeHlvJIkSNljhgqFw+ltW/kq4rDs3AbR7Rwk0flK1crvhQ2FUHgb+nq9xIVAwkrKjlDyhupnaExFNCTtkEAS3gML3qb6IW0ZplFFwvG3cpeukx+zE3p8sR1xSfcN7yLoTRLYZWnw1jiX8Z+HSrQFhGroZVCv98ttAzO/WErLXKnupDsqLw8YkBBaEmWcseuR736KkvrCJIT+VsdENHtO/kUJaIbI55FZobNqr4JtfsUPwSj2SqncfnyRBSLaJqUG5aeR1JPvgRHw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
