travis:
  secure:
    BINSTAR_TOKEN: AdLLO7oRWER3gtLi9AFewFAUlzvjvNFvdWjZw5jvAn3/1x1th9jLqdd1gq1n2vn7mcsZOURwtzx13rCNXTKoJtsW1OddubJgoddB9UvLAFPvd2bHLwMmuGYrB+IYXI5zs6kBQmv1K8z0mBqi/G3IsZ1xiGLGxr+BfH7I+Tnvk8r52sdoUVbvHGCqN59AngBsaMGw9B/aFkiAuA/Hwva9EMfji6A8nKJRdawbxOJllmzOWPNpugIaky7a2pCKiZF8Eenp/H/IttyiuHfAVYH/w59LdYl+uZmI4gTqNA8zJVxDx3HPxlEOKyer5kgUnZuuNn4yIy0yhEYN2jW6nM7X0MnzsWwc09tnHrruOzhHrlEJvPtVxldnCr01vD8FGqr12wt9EtzyAr0fG6mi72tjvkZFYCf6Uznm2EmrisqGU8wHhPDPVcrEC6xy6RcnDE82yoGCichPsTFFwqOf5G6SwHJeMNhK+NLfySBwEaryLKEo0RFBfVHNXER8RvvzoyYwQ7h/5Tvsn4ZZf7jQlljrxrqJhwvfiubnxhEon6GKBwBISj9IhsMT/4a3dSkv/34AmLYDUbzP3o65VGz1ZRO/tjMK52F89BR8pcXN89iiWEddlbHio+y76yhiLGJ6qKHLBydQEg59/VcOGudrwJDhT0lyic/SFDu61XXAncAuPek=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
