travis:
  secure:
    BINSTAR_TOKEN: X06ddFSlWhcyJ4KJMTHEhIfJgdF/lQ6VQ+pDXi09ll/K7255DY4eqeIfi8qzOoMW4lyXSYwVlSoKIfEBwD6aiuNkA/HzZgcK1QOhU+NszVSUwAQxb7LPF0oSc/5DXHY5YJAc3nQ+0fZdnpvNa4iXiE3ZfI2MuPEXhH/85Gu+FuHXFbZy/pehTuQOytGL/UHqcRnM+i/7P6R1XFfc2WSs44GgN++/JFrWXM2NgR0vaevl82rX7AwfVVmBxDn3DWGLYZ+YHnOO2gYceAluVebXwDR62sHcIYjTrC2SnJIoGLLOmc4bIvig6EaFe5Dc2dE6VIejbl3pMEOWX0N3UN42SUuhPSGQdDHLMadzYs0xOx0T9M+3WRqNze4lwGdToE7ga2npaFBwUfHC/kjhvGoHei5CXFt3ShaqUlwm0Uw/oUrx9ZARS6lOv+ye1nTgYJ4KXv5pL+JBI8LE8kY3w7sonpfJGDW3mV0V+x6Z4T/YaOwHC6NvAwv2u71IJbwm9ShnY763UwjWN9j4xINqhXTxVzELOQnUptTYd/vQ9qn1UthQ3o39FT5jGI51R8m+6Fxsf/LxJiCzXxvhdhUHCwuFiAWfNeT/8J5sBFgMCd4whJrwp9UfVmX3scTWx28cRBVW6LyuEKmkZx+TGhK4fAv/ooppmlI4tJ7QcPEzDH4inwI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
